server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: model_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: model_logs
          __path__: /team-2/data/*.txt
  - job_name: kafka_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: kafka_logs
          __path__: /path/to/kafka/logs/*.log
